### ISSUE TITLE
Tracking issue - Updating from githubteacher/gitterbot

### ISSUE THREAD

**Issue by brianamarie** [satelliteworkshops/gitterbot#1]
`githubteacher/gitterbot` is currently functional. This issue tracks the steps to get this repository functional and ready to work with for run-throughs, brown bags, or workshop sessions.

- [x] Update with code from `githubteacher/gitterbot` master branch
- [x] Put outline from services repository into `readme`
- [x] Contact `dcscan` or `berkeleytrue` for 👀 
  - Review/feedback
  - Attribution 
- [x] Contact `madlittlemods` about support from Gitter on day of workshop (May 23rd, London) and possibly brownbag (April 13th, 11am PST)

**Comment by brianamarie** [comment]
@dcsan @berkeleytrue 👋 This is a workshop outline based off of the fantastic work done in `dcsan/gitterbot` with a goal of getting users up and running with their own bot. I'd love to have your thoughts on the current state of it, especially since it's been changed quite a bit. 

The `README.md` _should_ have the steps outlined in detail so that you could go through and try it yourselves. If you have time, would you be willing to review it? 

Regardless of if you have time to review, I want to make sure we give proper credit where it's due. Since the README has changed, are there any other ways you'd like us to give credit during the workshop or in this repo?

**Comment by brianamarie** [comment]
@madlittlemods We've chatted briefly in the Gitter developers room. (You helped me unblock my bot after it got hellbanned in an unfortunate looping incident.) 

We are going to be using Gitter in this same capacity at GitHub Satellite in May. We would really ❤️ some backup from Gitter in case something like this were to happen during the workshop on May 23rd in London. Would this be possible?

**Comment by MadLittleMods** [comment]
@brianamarie Feel free to ping again to unblock. Just create an issue on the repo, https://github.com/gitterHQ/gitter

**Comment by dcsan** [comment]
hiya - congrats on getting this going!

you might want to add code to prevent a feedback loop happening? one way is to just cache the previous message and do a comparison on sending - so you don't send the same message twice (or more!)

there were some other features in the gitterbot such as adding content to a github wiki (knowledge base) that maybe useful to people too...

good luck!

**Comment by dcsan** [comment]
also I'm not familiar with githubteacher, but you've obviously updated the README to remove the old junk like iojs. 
FCC also did a fork (or rather, just copied the repo) for the bot, so there maybe some updated code there to look at, although I don't think much was done other than fixing typos here and there.

**Comment by brianamarie** [comment]
> @brianamarie Feel free to ping again to unblock. Just create an issue on the repo, https://github.com/gitterHQ/gitter

@MadLittleMods Fantastic, thank you. My main concern is for the day of the workshop. If there is an issue, any time that we are waiting for someone to respond to a ping would eat into the time significantly. Having someone from Gitter on call during the workshop times would give us more confidence. Is this possible? 



> you might want to add code to prevent a feedback loop happening? one way is to just cache the previous message and do a comparison on sending - so you don't send the same message twice (or more!)

@dcsan This is a great idea! @migarjo What do you think on this?

**Comment by migarjo** [comment]
@brianamarie, that sounds great! I'll try to have a PR submitted for that before tomorrow

**Comment by MadLittleMods** [comment]
@brianamarie Easiest way for me to see:

> Just create an issue on the repo
>
> https://github.com/satelliteworkshops/gitterbot/issues/1#issuecomment-291979769

**Comment by brianamarie** [comment]
Thanks all for help! Closing now as all items are done or in motion. 👍
