### ISSUE TITLE
Backup Bot tracking issue

### ISSUE THREAD

**Issue by brianamarie** [satelliteworkshops/gitterbot#3]
In the event that the Bot gets banned, it would be a good backup. The plan now is to open an issue in Gitter's repo, but this would be an instant backup that we'd have more control over. 

To set this up, we need to:
- [x] Create another bot account, `githubstudent`
- [x] Have the bot join the chat room
- [x] Create a separate .env setup
- [x] Test

**Comment by brianamarie** [comment]
Original .env:

```
SERVER_ENV=demobot
GITTER_USER_TOKEN=92123753cc1ec6e60bd0ca3e7b87b35bc38ca4d3
FCC_API_KEY=TESTAPIKEY
GITTER_APP_KEY=63ece8ac0eeed9b17b1cc9867f65d4857ec6e5fc
GITTER_APP_SECRET=9026e3b3a74357035ee15a9591f31b2de5cfd3a6
GITTER_APP_REDIRECT_URL=http://localhost:7891/login/callback
LOG_LEVEL=10
PORT=7891
```

new .env for githubstudent: 
```
SERVER_ENV=demobot
GITTER_USER_TOKEN=338ca32655549d35115cd82281b522cf57634b26
FCC_API_KEY=TESTAPIKEY
GITTER_APP_KEY=63ece8ac0eeed9b17b1cc9867f65d4857ec6e5fc
GITTER_APP_SECRET=9026e3b3a74357035ee15a9591f31b2de5cfd3a6
GITTER_APP_REDIRECT_URL=http://localhost:7891/login/callback
LOG_LEVEL=10
PORT=7891
```

**Comment by brianamarie** [comment]
cc @migarjo for 👀, closing now but if we need it the info is all here 🎉
